# Generated by Django 4.1.2 on 2022-10-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('part', 'Part Time'), ('full', 'Full Time')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
