# Generated by Django 4.1.2 on 2022-10-13 13:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_experience_years_job_published_at_job_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
